# Generated by Django 2.1.3 on 2018-12-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(choices=[('gaming', 'GAMING'), ('sports', 'SPORTS'), ('films', 'FILMS'), ('travel', 'TRAVEL'), ('reading', 'READING')], default='gaming', max_length=10),
        ),
    ]
